##  _   _      _ _
## | | | | ___| (_)_  __
## | |_| |/ _ \ | \ \/ /
## |  _  |  __/ | |>  <
## |_| |_|\___|_|_/_/\_\
##
## Check the full docs at docs.helix-editor.com.
## Matteo Giorgi (https://www.geoteo.net/)


theme = "hembox"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
