#!/usr/bin/env bash

# This script searches all opened windows and uses fzf to select one of them.
# It is intended to be used as such: i3-sensible-terminal -T __600x200__ -e i3windows.
# Here there's few sorting alternatives to the ones used below: sort -k1n; sort -n -k1.1; sort -V.


[[ -x "$(command -v wmctrl)" && -x "$(command -v fzf)" ]] || exit 1
WINTOGO=$(wmctrl -d | awk '{print $1, $NF}' | while read -r WSNUM WSNAME; do wmctrl -l | \
        grep -v __scratch_0__ | grep -v __scratch_1__ | grep -v __scratch_2__ | grep -v __scratch_3__ | grep -w "$WSNUM" | \
        awk -v WSNAME="$WSNAME" '{ $2=$3=""; $1=" "$1; sub(/  /," "); print WSNAME, $0 }'; done | sort -V | fzf `
            `--ansi `
            `--prompt='i3windows > ' `
            `--height 100% `
            `--margin 0% `
            `--reverse `
            `--info=hidden `
            `--bind 'ctrl-h:cancel' `
            `--bind 'ctrl-n:half-page-down' `
            `--bind 'ctrl-p:half-page-up')
[[ -n "$WINTOGO" ]] || exit 1

echo "$WINTOGO" | awk '{print $2}' | xargs -I{} wmctrl -i -a {}
